Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
